### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by sleepycat** [waseem18/node-rake#2]
At the moment there are no tests for this library.
If I were to send a pull request with tests, is there a preferred test framework I should use?
My default these days is Facebook's [Jest](https://facebook.github.io/jest/).

**Comment by waseem18** [comment]
Even I was planning to use Jest for tests!

**Comment by sleepycat** [comment]
Jest it is then!

**Comment by waseem18** [comment]
@sleepycat Updated version, it's 0.0.8 now! Changed regex which would improvise results.
