### ISSUE TITLE
Passing my own stopwords list

### ISSUE THREAD

**Issue by icaroponce** [waseem18/node-rake#8]
Hi, 

I'd like to make this module work using my own stopwords list. 
Is there a way to do it and I missed it? If not, can I send a PR adding this functionality?

Thanks.

**Comment by waseem18** [comment]
With the current version of npm module, you can't specifically mention the stopwords that you need.

Good to see that you're interested in adding this functionality. By the way how are you planning to do that?

**Comment by icaroponce** [comment]
Well, as the API is very simple, I was thinking about passing a `opts` object to the constructor, which could offer more versatility and still keeps it simple. Something like that: 

```js
const rake = require('node-rake');
const myStopwords = ['the', 'my'];

const opts = { stopwords: myStopwords };

rake.generate("The text to test my stopwords", opts);
```
So, this way we can check if the user provided a stopwords list, if not, we just use the file list.
The second point about the `opts` object here is that it can easily be used for other customization in the future. 

Actually, I have already something very similar implemented. What do you think? If you have a different suggestion, please let me know.

**Comment by waseem18** [comment]
Great! Looking forward for your PR :)

**Comment by icaroponce** [comment]
Thanks for the opportunity to contribute!

As soon as I have more free time I'm gonna send the PR.

Kind regards
